apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytbt-deployment
  labels:
    app: ytbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ytbot
  template:
    metadata:
      labels:
        app: ytbot
    spec:
      containers:
        - name: ytbot
          image: jackwright3898/ytbot:latest
          env:
            - name: NODE_ENV
              value: production
            - name: DISCORD_TOKEN
              value: ""
            - name: CLIENT_ID
              value: ""
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"