# SHARD MANAGER APPLICATION DEPLOYMENT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytbot-sm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ytbot-shard-manager
  template:
    metadata:
      labels:
        app: ytbot-shard-manager
    spec:
      containers:
        - name: ytbot-shard-manager
          image: ytbot-shard-manager
          imagePullPolicy: Never
          env:
            - name: SHARD_MANAGER_URL
              value: http://ytbot-sms:3000
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
          volumeMounts:
            - name: ytbot-dotenv
              mountPath: /home/node/.env
              subPath: .env
              readOnly: true
      volumes:
        - name: ytbot-dotenv
          secret:
            secretName: ytbot-dotenv-file